import { MedicalObject } from "../types";

export const adminMedicalObjects: MedicalObject[] = [
  {
    id: 1,
    name: "Respublika Shoshilinch Tibbiy Yordam Ilmiy Markazi",
    type: "Shifoxona",
    ownership: "Davlat",
    region: "Toshkent shahri",
    district: "Chilonzor tumani",
    mahalla: "Katta Chilonzor",
    address: "Kichik halqa yo'li, 2",
    inn: "201122334",
    position: { lat: 41.2825, lng: 69.2043 },
    coordinateStatus: "valid",
    moderationStatus: "approved",
    activityStatus: "active",
    lastModified: "2024-03-15 10:30",
  },
  {
    id: 2,
    name: "Shox Med Center",
    type: "Klinika",
    ownership: "Xususiy",
    region: "Toshkent shahri",
    district: "Mirzo Ulug'bek tumani",
    mahalla: "Oqqo'rg'on",
    address: "Buyuk Ipak Yo'li, 15",
    inn: "301122334",
    position: { lat: 41.3392, lng: 69.3381 },
    coordinateStatus: "valid",
    moderationStatus: "approved",
    activityStatus: "active",
    lastModified: "2024-03-14 16:45",
  },
  {
    id: 3,
    name: "Dori-Darmon Sergeli",
    type: "Dorixona",
    ownership: "Davlat",
    region: "Toshkent shahri",
    district: "Sergeli tumani",
    mahalla: "Ittifoq",
    address: "Yangi Sergeli yo'li",
    inn: "401122667",
    position: { lat: 41.2298, lng: 69.2215 },
    coordinateStatus: "valid",
    moderationStatus: "pending_review",
    activityStatus: "active",
    lastModified: "2024-03-16 09:15",
  },
  {
    id: 4,
    name: "Central Lab Diagnostics",
    type: "Laboratoriya",
    ownership: "Xususiy",
    region: "Toshkent viloyati",
    district: "Zangiota tumani",
    address: "Toshkent halqa yo'li",
    inn: "501122889",
    position: { lat: 41.15, lng: 69.15 },
    coordinateStatus: "missing",
    moderationStatus: "needs_changes",
    activityStatus: "active",
    lastModified: "2024-03-12 11:20",
  },
  {
    id: 5,
    name: "Eski Shahar Poliklinikasi",
    type: "Poliklinika",
    ownership: "Davlat",
    region: "Samarqand viloyati",
    district: "Samarqand shahri",
    address: "Registon ko'chasi, 45",
    inn: "209988776",
    position: { lat: 39.65, lng: 66.97 },
    coordinateStatus: "invalid",
    moderationStatus: "rejected",
    activityStatus: "archived",
    lastModified: "2024-02-28 14:00",
  },
  {
    id: 6,
    name: "Yangi Hayot Shifoxonasi (Loyiha)",
    type: "Shifoxona",
    ownership: "Xususiy",
    region: "Farg'ona viloyati",
    district: "Marg'ilon shahri",
    address: "Mustaqillik ko'chasi",
    inn: "305544332",
    position: { lat: 40.47, lng: 71.72 },
    coordinateStatus: "valid",
    moderationStatus: "draft",
    activityStatus: "active",
    lastModified: "2024-03-16 12:00",
  }
];
