import { ObjectChangeRequest } from "../types";

export const mockChangeRequests: ObjectChangeRequest[] = [
  {
    id: "REQ-001",
    object_id: 2,
    object_name: "Shox Med Center",
    requested_by_name: "Aziz Toshkentov",
    requested_by_role: "Muassasa direktori",
    type: "update",
    status: "pending",
    priority: "normal",
    region: "Toshkent shahri",
    district: "Mirzo Ulug'bek tumani",
    before_data: {
      phone: "+998 71 123 45 67",
      email: "old@shoxmed.uz",
    },
    after_data: {
      phone: "+998 90 777 00 11",
      email: "info@shoxmed.uz",
      work_hours: "24/7",
    },
    reason: "Aloqa ma'lumotlari yangilandi va ish tartibi 24 soatlikka o'tdi.",
    created_at: "2024-03-20 10:30",
    updated_at: "2024-03-20 10:30",
  },
  {
    id: "REQ-002",
    object_name: "Yangi Hayot Xususiy Klinikasi",
    requested_by_name: "Malika Ortiqova",
    requested_by_role: "Operator",
    type: "create",
    status: "pending",
    priority: "high",
    region: "Samarqand viloyati",
    district: "Samarqand shahri",
    after_data: {
      name: "Yangi Hayot Xususiy Klinikasi",
      type: "Klinika",
      ownership: "Xususiy",
      inn: "305544332",
      address: "Amir Temur ko'chasi, 12",
      position: { lat: 39.65, lng: 66.95 },
    },
    reason: "Yangi litsenziyalangan xususiy klinika qo'shildi.",
    created_at: "2024-03-19 15:45",
    updated_at: "2024-03-19 15:45",
  },
  {
    id: "REQ-003",
    object_id: 5,
    object_name: "Eski Shahar Poliklinikasi",
    requested_by_name: "Botir Aliyev",
    requested_by_role: "Moderator",
    type: "archive",
    status: "pending",
    priority: "normal",
    region: "Samarqand viloyati",
    district: "Samarqand shahri",
    after_data: {
      activityStatus: "archived",
    },
    reason: "Muassasa faoliyati to'xtatilgan, bino rekonstruksiyaga yopilgan.",
    created_at: "2024-03-18 09:00",
    updated_at: "2024-03-18 09:00",
  },
  {
    id: "REQ-004",
    object_id: 3,
    object_name: "Dori-Darmon Sergeli",
    requested_by_name: "Sardor Karimov",
    requested_by_role: "Admin",
    type: "delete",
    status: "needs_changes",
    priority: "low",
    region: "Toshkent shahri",
    district: "Sergeli tumani",
    after_data: {},
    reason: "Ma'lumotlar xato kiritilgan deb hisoblayman.",
    admin_comment: "Iltimos, aynan qaysi ma'lumotlar xatoligini ko'rsatib o'ting va asosi keltiring.",
    created_at: "2024-03-17 11:20",
    updated_at: "2024-03-18 14:00",
  },
  {
    id: "REQ-005",
    object_id: 1,
    object_name: "Respublika Shoshilinch Tibbiy Yordam Ilmiy Markazi",
    requested_by_name: "Super Admin",
    requested_by_role: "Super Admin",
    type: "update",
    status: "approved",
    priority: "normal",
    region: "Toshkent shahri",
    district: "Chilonzor tumani",
    before_data: {
      position: { lat: 41.28, lng: 69.20 },
    },
    after_data: {
      position: { lat: 41.2825, lng: 69.2043 },
    },
    reason: "Koordinatalar aniqlashtirildi.",
    created_at: "2024-03-15 08:30",
    updated_at: "2024-03-15 09:00",
    reviewed_at: "2024-03-15 09:00",
    reviewed_by: "Super Admin",
  }
];
